version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mid_term_project_book_store
    ports:
      - "5432:5432"
    networks:
      - web-services

networks:
  web-services:
    driver: bridge

volumes:
  postgres-data: